apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::645742385858:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::645742385858:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LX2T5O2NTRG6
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-06T18:28:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "868"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 78d452c0-7834-11ea-9b62-0e935bc7b71e
